
shadow = false  # Don't draw shadows around stacked views
borders = "simple"  # Alternatives are "none" and "outset"

[colors]
    background = "default"
    shadow     = ["#000000", "black"]
    view       = "default"

    primary   = ["white"]
    secondary = "white"
    tertiary  = "white"

    title_primary   = "green"
    title_secondary = "green"

    highlight          = "red"
    highlight_inactive = "light white"
    highlight_text = "black"
