//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::album::Entity as Album;
pub use super::artist::Entity as Artist;
pub use super::genre::Entity as Genre;
pub use super::song::Entity as SongEntity;
pub use super::song_album_junction::Entity as SongAlbumJunction;
pub use super::song_artist_junction::Entity as SongArtistJunction;
pub use super::song_genre_junction::Entity as SongGenreJunction;
pub use super::song_youtube_playlist_id_junction::Entity as SongYoutubePlaylistIdJunction;
pub use super::youtube_playlist_id::Entity as YoutubePlaylistId;
