//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "youtube_playlist_id")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub youtube_playlist_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::song_youtube_playlist_id_junction::Entity")]
    SongYoutubePlaylistIdJunction,
}

impl Related<super::song::Entity> for Entity {
    fn to() -> RelationDef {
        super::song_youtube_playlist_id_junction::Relation::Song.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::song_youtube_playlist_id_junction::Relation::YoutubePlaylistId
                .def()
                .rev(),
        )
    }
}

impl Related<super::song_youtube_playlist_id_junction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SongYoutubePlaylistIdJunction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
