//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

pub type GenreModel = Model;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "genre")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub genre: String,
}

impl Default for Model {
    fn default() -> Self {
        Self {
            id: 0,
            genre: "Unknown".to_string(),
        }
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::song_genre_junction::Entity")]
    SongGenreJunction,
}

impl Related<super::song::Entity> for Entity {
    fn to() -> RelationDef {
        super::song_genre_junction::Relation::Song.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::song_genre_junction::Relation::Genre.def().rev())
    }
}

impl Related<super::song_genre_junction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SongGenreJunction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
