//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod album;
pub mod artist;
pub mod genre;
pub mod song;
pub mod song_album_junction;
pub mod song_artist_junction;
pub mod song_genre_junction;
pub mod song_youtube_playlist_id_junction;
pub mod youtube_playlist_id;
